jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${ENCRYPTION_PASSWORD}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# https://medium.com/@dharampro/3-ways-to-tune-apache-tomcat-in-spring-boot-891691915cb2
server:
  port: 8090
  tomcat:
      protocol: "org.apache.coyote.http11.Http11AprProtocol"



spring:
  mail:
    #protocol: smtp
    #host: mail.smtp2go.com
    host: smtp-relay.brevo.com
    #port: 2525
    port: 587
    username: goosseff8@gmail.com
    password: ENC(h/xFDE6dFW0KA4wQ095PNKWXkxhINGF8zsOnGdjBr2U=)


  datasource:
    username: root
    password: ENC(YYFzPCtacd3rqELvxX9IkO68aaeMlax6)
    url: jdbc:mysql://localhost:3306/registerUser?useSSL=false&serverTimezone=Europe/Moscow
    #river-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true


mail:
  enabled: true
  from: vitaly.gusev@progforce.com
  subject: כשלון בריצת ממשק מניפה ארכיב


